email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        ESPLUGUES_ID = "8077"
        WORKING_DIR = "/tmp/esplugues"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current/"
        // XBRL_FILE = "AJ-TrimLoc-20194t.xbrl"
        // YEAR = 2019
    }
    stages {
        stage('Extract > Download data sources') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/download-s3/run.rb 'esplugues/budgets/${XBRL_FILE}' ${WORKING_DIR}"
            }
        }
        stage('Transform > Transform planned budgets files') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/xbrl/penloc/transform-planned/run.rb operations/gobierto_budgets/xbrl/dictionaries/xbrl_penloc_dictionary.yml ${WORKING_DIR}/${XBRL_FILE} ${ESPLUGUES_ID} ${YEAR} ${WORKING_DIR}/budgets-planned-${YEAR}.json"
            }
        }
        stage('Load > Import planned files') {
            steps {
              sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/import-planned-budgets/run.rb ${WORKING_DIR}/budgets-planned-${YEAR}.json ${YEAR}"
            }
        }
        stage('Load > Calculate totals') {
          steps {
            sh "echo ${ESPLUGUES_ID} > ${WORKING_DIR}/organization.id.txt"
            sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/update_total_budget/run.rb '${YEAR}' ${WORKING_DIR}/organization.id.txt"
          }
        }
        stage('Load > Calculate bubbles') {
          steps {
            sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/gobierto_budgets/bubbles/run.rb ${WORKING_DIR}/organization.id.txt"
          }
        }
        stage('Load > Calculate annual data') {
          steps {
            sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto_budgets/annual_data/run.rb '${YEAR}' ${WORKING_DIR}/organization.id.txt"
          }
        }
        stage('Load > Publish activity') {
          steps {
            sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/publish-activity/run.rb budgets_updated ${WORKING_DIR}/organization.id.txt"
          }
        }
        stage('Clear cache') {
          steps {
            sh "cd ${GOBIERTO}; bin/rails runner ${GOBIERTO_ETL_UTILS}/operations/gobierto/clear-cache/run.rb"
          }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}
