email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        FOLDER = "budgets"
        PATH = "$HOME/.rbenv/shims:$PATH"
        ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        DATASET_NAME = "Proveedores y facturas"
        DATASET_SLUG = "proveidors-factures"
        DATASET_TABLE_NAME = "providers_invoices"
        // Variables that must be defined via Jenkins UI:
        // ENVIRONMENT = ""
        // GOBIERTO_DATA_DEST_URL = ""
        // ETL = "/var/www/gobierto-etl-esplugues/current/"
    }
    options {
        retry(3)
    }
    stages {
        stage('Import budgets') {
            steps {
              sh '''#!/bin/bash
                source ${ETL}/.rbenv-vars;
                cd ${ETL_UTILS};
                ruby operations/gobierto_data/upload-dataset/run.rb \
                  --api-token $WRITE_API_TOKEN \
                  --name "$DATASET_NAME" \
                  --slug $DATASET_SLUG \
                  --table-name $DATASET_TABLE_NAME \
                  --gobierto-url $GOBIERTO_DATA_DEST_URL \
                  --file-url "https://gobierto-populate-${ENVIRONMENT}.s3.eu-west-1.amazonaws.com/gobierto_budgets/8077/data/providers/2020.csv" ;
                for year in {2018..2019}; do
                  ruby operations/gobierto_data/upload-dataset/run.rb \
                    --api-token $WRITE_API_TOKEN \
                    --name "$DATASET_NAME" \
                    --slug $DATASET_SLUG \
                    --table-name $DATASET_TABLE_NAME \
                    --gobierto-url $GOBIERTO_DATA_DEST_URL \
                    --file-url "https://gobierto-populate-${ENVIRONMENT}.s3.eu-west-1.amazonaws.com/gobierto_budgets/8077/data/providers/${file}.csv"
                    --append;
                done
              '''
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email
        }
    }
}

