email = "popu-servers+jenkins@populate.tools "
pipeline {
    agent any
    environment {
        PATH = "$HOME/.rbenv/shims:$PATH"
        GOBIERTO_ETL_UTILS = "/var/www/gobierto-etl-utils/current/"
        ESPLUGUES_ETL = "/var/www/gobierto-etl-esplugues/current/"
        WORKING_DIR = "/tmp/esplugues"
        PAM_SLUG = "pam-2016-2019"
        // Variables that must be defined via Jenkins UI:
        // GOBIERTO = "/var/www/gobierto/current/"
        // ESPLUGUES_DOMAIN="portalobert.esplugues.cat"
    }
    stages {
        stage('Extract > Download data sources') {
            steps {
                sh "cd ${ESPLUGUES_ETL};  ${WORKING_DIR}/plan.json"
            }
        }
        stage('Extract > Check JSON format') {
            steps {
                sh "cd ${GOBIERTO_ETL_UTILS}; ruby operations/check-json/run.rb ${WORKING_DIR}/plan.json"
            }
        }
        stage('Load > Import plans') {
            steps {
                sh "cd ${GOBIERTO}; bin/rails runner ${ESPLUGUES_ETL}/operations/gobierto_plans/importer/run.rb ${WORKING_DIR}/plan.json ${ESPLUGUES_DOMAIN} ${PAM_SLUG}"
            }
        }
    }
    post {
        failure {
            echo 'This will run only if failed'
            mail body: "Project: ${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER} - URL de build: ${env.BUILD_URL}",
                charset: 'UTF-8',
                subject: "ERROR CI: Project name -> ${env.JOB_NAME}",
                to: email

        }
    }
}
